spring.application.name=insurance

#DB settings

spring.datasource.url=jdbc:mysql://host.docker.internal:3306/automobile_insurance_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=keerthana@21

# hibernate connection

spring.jpa.hibernate.ddl-auto=update